name: Generate Allure Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Allure CLI
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          tar -zxvf allure-2.27.0.tgz
          sudo mv allure-2.27.0 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure
          allure --version

      - name: Build & Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report
          rm -rf docs
          mkdir docs
          cp -r allure-report/* docs/

      - name: Commit and Push Allure Report
        run: |
          git config --global user.email "pramila.lamba5@gmail.com"
          git config --global user.name "Pramila91"
          git add docs/
          git commit -m "Auto-update Allure report [skip ci]" || echo "No changes to commit"
          git push
